#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# equivalent de $router->get('/', 'DefaultController@index')



# config/routes.yaml

#about:
#    path: /a-propos
#    controller: App\Controller\PagesController::about